### ISSUE TITLE
Wrong repo url

### ISSUE THREAD

**Issue by evgar** [erquhart/gatsby-netlify-cms-example#2]
Hi there!
You had a wrong repo url in your readme.
**gatsby new gatsby-site https://github.com/gatsbyjs/gatsby-netlify-cms-example**
instead of 
gatsby new gatsby-site https://github.com/erquhart/gatsby-netlify-cms-example

And thank you for tutorial)

**Comment by erquhart** [comment]
Fixed, thanks!
