### ISSUE TITLE
Sourcing folder from different repo

### ISSUE THREAD

**Issue by haxmax** [erquhart/gatsby-netlify-cms-example#9]
This is a Question : 

Can we have a blog folder from example in another github repo?

For example:  we have two github repo:
    - WebApplication Repo
    - Content Repo

What should be the best way to store content in content Repo after saving the content from Netlify CMS and pull up in WebApplication Repo during gatsby build.

**Comment by erquhart** [comment]
I don't have particulars but I can point you in the general direction that I would go:

- Create a GitHub source plugin using the GitHub API - this is the bulk of the work, here's a [tutorial](https://www.gatsbyjs.org/docs/pixabay-source-plugin-tutorial/).
- Use the GitHub source plugin you created to pull in content from your content repo during build
- Trigger Netlify builds from both repos - one will be automatic, the Gatsby app repo connected to the Netlify site, the content repo can trigger by using a [webhook](https://www.netlify.com/docs/webhooks/).
